title: Dcycle Blog
description: Drupal automated tests, continuous integration

url: https://alberto56.github.io
baseurl: "/dcycleblog"
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate, jekyll-redirect-from]
paginate: 10

navigation:
 - title: Blog
   url: /
 - title: Manifesto
   url: /manifesto
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: alberto56
   twitter: alberto56
   email: albert@dcycle.com

google_analytics: "UA-25649530-1"
